const DEFAULT_STATE={day:1,streak:0,learned:{},correct:0,total:0,weak:[],pitchScores:[],simStep:0,messages:[],srs:{},daily:{},voiceScores:[],courseMode:"30",lastStudyDate:""};
const state=Object.assign({},DEFAULT_STATE,JSON.parse(localStorage.getItem("investorCoachState")||"null")||{});
state.learned=state.learned||{};state.weak=state.weak||[];state.srs=state.srs||{};state.daily=state.daily||{};state.messages=state.messages||[];state.pitchScores=state.pitchScores||[];state.voiceScores=state.voiceScores||[];
state.coachStats=state.coachStats||{};state.coachPlan=["7","30"].includes(state.coachPlan)?state.coachPlan:"30";state.coachPlanDays=state.coachPlanDays||{"7":state.coachDay||1,"30":1};state.coachRecent=Array.isArray(state.coachRecent)?state.coachRecent.slice(-12):[];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem("investorCoachState",JSON.stringify(state));
const toast=m=>{const t=$("#toast");if(!t)return;t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
const pct=(a,b)=>b?Math.round(a/b*100):0;const term=id=>TERMS.find(x=>x.id===id);const today=()=>new Date().toISOString().slice(0,10);
const CATEGORY_ORDER=["Метрики","Рынок","Финансы","Фандрайзинг","Рост","Бизнес","Коммуникация","Право"];
const SRS_DAYS=[0,1,3,7,14,30,60];
function srsInfo(id){if(!state.srs[id])state.srs[id]={box:0,due:today(),right:0,wrong:0,last:""};return state.srs[id]}
function addDays(dateStr,n){const d=new Date((dateStr||today())+"T12:00:00");d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function updateSRS(id,ok){const s=srsInfo(id);if(ok){s.box=Math.min(6,(s.box||0)+1);s.right=(s.right||0)+1}else{s.box=Math.max(0,(s.box||0)-1);s.wrong=(s.wrong||0)+1} s.last=today();s.due=addDays(today(),SRS_DAYS[s.box]);state.learned[id]=true;const wi=state.weak.indexOf(id);if(ok&&s.box>=2&&wi>=0)state.weak.splice(wi,1);if(!ok&&wi<0)state.weak.unshift(id);save()}
function dueTerms(){return TERMS.filter(t=>{const s=state.srs[t.id];return s&&s.due<=today()}).sort((a,b)=>{const A=srsInfo(a.id),B=srsInfo(b.id);return (B.wrong-B.right)-(A.wrong-A.right)})}
function mastery(){if(!TERMS.length)return 0;return Math.round(TERMS.reduce((n,t)=>n+Math.min(1,(srsInfo(t.id).box||0)/5),0)/TERMS.length*100)}
function studiedToday(){return Object.values(state.srs).filter(x=>x.last===today()).length}
function setDaily(key){state.daily[key]=today();save();renderDashboard()}
function doneDaily(key){return state.daily[key]===today()}
function safe(s){return String(s??"").replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]))}

function renderDashboard(){const avg=pct(state.correct,state.total),master=mastery();
$("#view-dashboard").innerHTML=`
<div class="grid grid-2"><div class="card hero"><div class="eyebrow hero-eyebrow">INVESTOR COACH</div><h2>Учитесь. Отвечайте. Практикуйтесь.</h2><p>Короткая теория, понятные тесты и голосовые встречи с инвестором.</p><div class="row"><button class="btn" onclick="go('coach')">Coach</button><button class="btn secondary" onclick="go('investor')">Встреча с инвестором</button></div></div>
<div class="card"><div class="eyebrow">ПРОГРЕСС</div><div class="metric">${master}%</div><div class="progress"><div style="width:${master}%"></div></div><p class="muted">Тесты: ${avg}% · Ответов: ${state.total}</p><button class="btn secondary" onclick="go('roadmap')">Открыть курс</button></div></div>
<div class="grid grid-4 stats-grid"><button class="card daily-task" onclick="go('coach')"><strong>Coach</strong><small>Главная тренировка</small></button><button class="card daily-task" onclick="go('learn')"><strong>Термины</strong><small>${TERMS.length} карточек</small></button><button class="card daily-task" onclick="go('speak')"><strong>Живая речь</strong><small>Объясняйте голосом</small></button><button class="card daily-task" onclick="go('investor')"><strong>Инвестор</strong><small>Голосовая встреча</small></button></div>`}

let learnCat="Все",learnQuery="";
function renderLearn(){const cats=["Все",...new Set(TERMS.map(t=>t.cat))];const list=TERMS.filter(t=>(learnCat==="Все"||t.cat===learnCat)&&(!learnQuery||(`${t.word} ${t.full} ${t.simple}`).toLowerCase().includes(learnQuery.toLowerCase())));
$("#view-learn").innerHTML=`<div class="card learn-intro"><h2>Термины</h2><input class="input" placeholder="Найти термин" value="${safe(learnQuery)}" oninput="learnQuery=this.value;renderLearn()"></div><div class="filterbar">${cats.map(c=>`<button class="${c===learnCat?'active':''}" onclick="setLearnCat('${c}')">${c}</button>`).join("")}</div><div class="grid grid-3">${list.map(t=>`<div class="card term-card"><div><span class="tag">${t.cat}</span><div class="term-word">${t.word}</div><div class="muted small">${t.full}</div><details class="recall-details"><summary>Показать объяснение</summary><p class="definition"><strong>Просто:</strong> ${t.simple}</p>${t.formula?`<div class="formula small"><strong>Формула:</strong> ${t.formula}</div>`:""}<p class="small"><strong>Пример:</strong> ${t.example||'Пример зависит от бизнеса.'}</p><p class="small"><strong>Инвестор может спросить:</strong> ${t.investor}</p><p class="small"><strong>Зачем знать:</strong> ${t.why}</p></details></div><div class="recall-actions"><button class="btn secondary" onclick="rateRecall('${t.id}',false)">Не знаю</button><button class="btn" onclick="rateRecall('${t.id}',true)">Знаю</button></div></div>`).join("")}</div>`}
function setLearnCat(c){learnCat=c;renderLearn()} function rateRecall(id,ok){updateSRS(id,ok);setDaily('learn');renderLearn();renderDashboard();toast(ok?'Следующее повторение отложено.':'Термин вернётся быстрее.')}


// Coach — главный адаптивный тренер: смысл → пример → логика инвестора → применение → повтор.
let coachSession=null;
const COACH_WEEK=[["cac","ltv","retention","churn","runway","burn","mrr","arr"],["gross_margin","payback","nrr","grr","arpu","arpa","conversion","cohort"],["tam","sam","som","bottom_up","icp","pmf","traction","competition"],["gtm","plg","sales_led","sales_cycle","pipeline","pricing","enterprise","saas"],["valuation","pre_money","post_money","dilution","cap_table","safe","term","milestone"],["liquidation","pro_rata","vesting","cliff","board","protective","due_diligence","data_room"],["pitch","pitch_deck","one_liner","ask","use_of_funds","why_now","founder_market","risk_register"]];
const COACH_PLANS={
 "7":{label:"7 дней",title:"Интенсив",pace:"2–4 часа в день",newPerDay:14,days:7,desc:"Быстрое погружение: термины → ситуации → вопросы инвестора → голосовая речь."},
 "30":{label:"30 дней",title:"Профессиональный курс",pace:"45–90 минут в день",newPerDay:4,days:30,desc:"Системное освоение языка инвесторов с интервальным повторением и живой практикой."}
};
const COACH_GUIDES={
cac:{benchmark:"CAC оценивают вместе с LTV, gross margin и payback. Сам по себе низкий CAC ничего не доказывает.",investorGoal:"Понять, можно ли масштабировать привлечение без разрушения экономики.",best:"Назовите CAC, сегмент, канал, период, динамику и payback."},
ltv:{benchmark:"Частый ориентир для подписочных моделей — LTV/CAC около 3× и выше, но LTV должен учитывать churn и маржу.",investorGoal:"Понять, сколько экономической ценности создаёт один клиент за всё время жизни.",best:"Покажите формулу LTV, retention/churn и отношение LTV к CAC."},
retention:{benchmark:"Универсального проходного retention нет. Смотрите когорты, частоту использования и стабилизацию retention со временем.",investorGoal:"Понять, возвращаются ли люди потому, что продукт действительно нужен.",best:"Покажите retention по когортам и периодам, подходящим вашей модели, плюс динамику новых когорт."},
churn:{benchmark:"Чем ниже churn, тем лучше, но норма зависит от сегмента. В SaaS полезно показывать logo churn и revenue churn отдельно.",investorGoal:"Понять, как быстро вы теряете клиентов и выручку и почему они уходят.",best:"Назовите churn за конкретный период, причины ухода и тренд по когортам."},
runway:{benchmark:"После раунда часто планируют примерно 12–18+ месяцев runway до следующего сильного milestone. Это ориентир, не правило.",investorGoal:"Понять, сколько времени у команды до следующей потребности в капитале.",best:"Назовите cash, net burn, runway и milestones, которые должны быть достигнуты."},
burn:{benchmark:"Burn оценивают по эффективности: сколько доказательств и роста компания получает на каждый потраченный доллар.",investorGoal:"Понять скорость расходования капитала и дисциплину управления.",best:"Покажите gross/net burn, runway и что именно этот burn покупает."},
gross_margin:{benchmark:"Для software/SaaS 70%+ часто воспринимается как сильный ориентир, но инфраструктурные и сервисные модели могут быть ниже.",investorGoal:"Понять качество выручки и сколько остаётся после прямой себестоимости.",best:"Назовите gross margin, состав COGS, динамику и эффект масштаба."},
payback:{benchmark:"Для SaaS payback до ~12 месяцев часто выглядит сильным; 12–18 месяцев может быть нормальным в enterprise при высоком ACV и удержании.",investorGoal:"Понять, как быстро возвращаются деньги, потраченные на привлечение.",best:"Назовите payback по сегментам и каналам и покажите динамику."},
nrr:{benchmark:"NRR выше 100% значит, что существующая база растёт без новых клиентов. 110–120%+ часто выглядит сильным в B2B SaaS, но зависит от сегмента.",investorGoal:"Понять, растёт ли выручка внутри существующих клиентов после churn и contraction.",best:"Покажите NRR по зрелым когортам и разложите expansion, contraction и churn."},
grr:{benchmark:"GRR показывает удержание без допродаж. Чем ближе к 100%, тем меньше утечка базовой выручки.",investorGoal:"Отделить реальное удержание от эффекта expansion revenue.",best:"Покажите GRR и NRR вместе."},
mrr:{benchmark:"Нет минимального MRR, который автоматически приводит к инвестиции. Важнее рост, retention и качество recurring revenue.",investorGoal:"Понять масштаб и предсказуемость ежемесячной повторяющейся выручки.",best:"Назовите MRR, рост, new/expansion/churned MRR и концентрацию клиентов."},
arr:{benchmark:"ARR оценивают вместе с growth rate, retention, gross margin и качеством контрактов.",investorGoal:"Понять годовой масштаб recurring revenue и скорость развития бизнеса.",best:"Покажите ARR, рост год-к-году, NRR/GRR и качество recurring revenue."},
conversion:{benchmark:"Нормальная conversion зависит от этапа и канала. Важнее bottleneck и динамика по cohort/channel.",investorGoal:"Понять, где пользователь переходит к следующей стадии ценности или оплаты.",best:"Покажите воронку по этапам, период, сегменты и изменения."},
tam:{benchmark:"Большой TAM полезен, но 1% огромного рынка без bottom-up логики слабый аргумент.",investorGoal:"Понять, достаточно ли велик конечный рынок для масштаба фонда.",best:"Дайте bottom-up TAM: число потенциальных клиентов × реалистичный annual spend."},
sam:{benchmark:"SAM должен отражать рынок, который реально обслуживает текущий продукт и география.",investorGoal:"Понять реальный доступный рынок вашей текущей модели.",best:"Покажите, какие сегменты TAM исключены и почему."},
som:{benchmark:"SOM должен быть достижимым, а не просто маленьким процентом TAM.",investorGoal:"Понять, какую часть рынка компания реально способна захватить.",best:"Свяжите SOM с каналами, sales capacity и временным горизонтом."},
pmf:{benchmark:"PMF не имеет одной магической цифры. Сильные сигналы: стабильный retention, willingness to pay, органический спрос и повторное использование.",investorGoal:"Понять, нашёл ли продукт рынок, который действительно его хочет.",best:"Покажите несколько независимых сигналов PMF, а не одну красивую метрику."},
traction:{benchmark:"Traction — не просто скачивания. Сильнее revenue, retention, usage, contracts и качественный pipeline.",investorGoal:"Понять, уменьшилась ли неопределённость бизнеса благодаря реальным данным.",best:"Назовите 2–4 метрики traction, период и темп изменения."},
gtm:{benchmark:"Сильный GTM повторяем: ясны ICP, канал, conversion, CAC, sales cycle и ответственный motion.",investorGoal:"Понять, как компания превращает рынок в предсказуемую выручку.",best:"Опишите ICP → канал → conversion → CAC → sales cycle → expansion."},
valuation:{benchmark:"Универсальной правильной valuation нет: она зависит от стадии, traction, рынка, условий и спроса на раунд.",investorGoal:"Понять, соответствует ли цена риску, upside и ownership фонда.",best:"Обоснуйте valuation стадией, traction, размером раунда и следующим milestone."},
dilution:{benchmark:"Нет одной идеальной dilution. Моделируйте этот и будущие раунды, option pool и контроль.",investorGoal:"Понять, как изменится ownership и мотивация команды.",best:"Покажите cap table до/после раунда на fully diluted basis."},
safe:{benchmark:"У SAFE нет универсально лучших cap/discount. Главное — понимать будущую конверсию и накопленный dilution.",investorGoal:"Понять экономику конвертации и скрытые обязательства cap table.",best:"Назовите тип SAFE, cap/discount, pro-rata/MFN при наличии и смоделируйте конверсию."},
term:{benchmark:"Term Sheet оценивают не только по valuation. Control и downside terms могут быть важнее нескольких процентов цены.",investorGoal:"Зафиксировать основные экономические и governance-условия сделки.",best:"Смотрите valuation, liquidation preference, board, protective provisions, pro-rata, option pool и vesting вместе."},
liquidation:{benchmark:"В venture часто встречается 1× non-participating preference; более жёсткие структуры требуют отдельного внимания.",investorGoal:"Понять порядок распределения денег при exit или ликвидации.",best:"Объясните multiple, participating/non-participating и seniority на простом числовом примере."},
cap_table:{benchmark:"Сильный cap table точный, прозрачный и без неожиданных прав или скрытых конвертируемых инструментов.",investorGoal:"Понять реальное ownership, dilution и обязательства перед держателями бумаг.",best:"Покажите current и pro-forma fully diluted cap table, включая options и SAFE/notes."},
due_diligence:{benchmark:"Критерий — не объём документов, а отсутствие расхождений между pitch и доказательствами.",investorGoal:"Проверить цифры, права, IP, клиентов, финансы и корпоративную историю.",best:"Организуйте data room так, чтобы ключевой тезис подтверждался документом за минуты."},
pitch:{benchmark:"Сильный pitch понятен без специальных знаний: проблема, клиент, решение, доказательство, рынок, модель, команда и ask.",investorGoal:"Быстро решить, достаточно ли интересна возможность для следующего шага.",best:"Говорите причинно: проблема → решение → доказательство → масштаб → почему вы → почему сейчас → ask."},
ask:{benchmark:"Ask должен финансировать конкретный следующий уровень доказательства, а не абстрактные маркетинг и развитие.",investorGoal:"Понять сколько капитала нужно, на какой срок и какой value-inflection он создаст.",best:"Сумма → runway → use of funds → измеримые milestones → состояние компании после их достижения."}
};
Object.assign(COACH_GUIDES,{
 arpu:{benchmark:"У ARPU нет универсального хорошего числа. Важно, растёт ли он и покрывает ли стоимость привлечения и обслуживания.",investorGoal:"Понять качество монетизации одного пользователя.",best:"Назовите ARPU по сегменту, динамику и связь с gross margin и CAC."},
 arpa:{benchmark:"Сильный ARPA устойчиво растёт без ухудшения churn и sales efficiency. Универсального порога нет.",investorGoal:"Понять монетизацию одного клиентского аккаунта.",best:"Покажите ARPA по сегментам и его динамику."},
 conversion:{benchmark:"Нормальная conversion зависит от этапа и канала. Инвестор смотрит на bottleneck, динамику и качество когорт.",investorGoal:"Понять, где пользователь переходит к следующей стадии ценности или оплаты.",best:"Покажите воронку по этапам, сегментам и каналам."},
 cap_table:{benchmark:"Сильный cap table — актуальный, юридически подтверждённый и понятный на fully diluted basis.",investorGoal:"Понять реальную структуру ownership и будущую dilution.",best:"Покажите founders, options, инвесторов и конвертируемые инструменты до/после раунда."},
 due_diligence:{benchmark:"Хороший diligence — когда каждое важное утверждение быстро подтверждается документом или данными.",investorGoal:"Проверить слова основателя и найти скрытые риски.",best:"Подготовьте corporate docs, cap table, IP, financials, KPI, contracts и customer evidence."}
});
function coachPlan(){return COACH_PLANS[state.coachPlan]||COACH_PLANS["30"]}
function coachDay(){const p=coachPlan();return Math.max(1,Math.min(p.days,Number(state.coachPlanDays[state.coachPlan]||1)))}
function setCoachPlan(id){if(!COACH_PLANS[id])return;state.coachPlan=id;if(!state.coachPlanDays[id])state.coachPlanDays[id]=1;coachSession=null;save();renderCoach();renderDashboard();pushAppHistory("coach",{coachSession:false})}
function termUse(t){const map={"Фандрайзинг":"Раунды, переговоры с инвесторами и условия сделки.","Финансы":"Финансовая модель, бюджет и экономика бизнеса.","Метрики":"Отчёты, рост продукта и вопросы инвестора о цифрах.","Рынок":"Оценка рынка, клиентов и конкурентов.","Рост":"Продажи, маркетинг и масштабирование.","Бизнес":"Бизнес-модель, продукт и монетизация.","Коммуникация":"Pitch, встречи и ответы инвестору.","Право":"Документы, права инвесторов и структура компании."};return map[t?.cat]||"В разговоре с инвестором и управлении стартапом."}
function coachGuide(t){const g=COACH_GUIDES[t.id]||{},goals={"Метрики":"Понять качество роста через цифры, а не впечатления.","Финансы":"Понять устойчивость экономики и потребность в капитале.","Рынок":"Понять кому нужен продукт и насколько велик рынок.","Рост":"Понять, можно ли повторяемо привлекать клиентов.","Фандрайзинг":"Понять экономику раунда, ownership и риски условий.","Право":"Понять контроль, права сторон и юридические риски.","Бизнес":"Понять как продукт создаёт ценность и выручку.","Коммуникация":"Понять, может ли основатель ясно объяснить бизнес."};let benchmark=g.benchmark;if(!benchmark)benchmark=(t.cat==="Метрики"||t.cat==="Финансы")?"Универсального проходного числа нет. Важно точное определение, период, динамика, сегмент и связь с соседними метриками.":"Универсального числового порога нет. Сильный ответ конкретный и подтверждён данными, примером или документом.";return {purpose:t.why||`Термин нужен, чтобы точно говорить о ${termUse(t).toLowerCase()}`,investorGoal:g.investorGoal||goals[t.cat]||"Понять конкретный риск или качество бизнеса.",benchmark,best:g.best||"Ответьте одним тезисом и подтвердите его цифрой, примером или документом.",use:termUse(t)}}
function coachStat(id){if(!state.coachStats[id])state.coachStats[id]={seen:0,right:0,wrong:0,streak:0,last:""};return state.coachStats[id]}
function coachAccuracy(id){const s=coachStat(id),n=(s.right||0)+(s.wrong||0);return n?s.right/n:0}
function coachLevel(id){const s=coachStat(id),a=coachAccuracy(id);if(s.seen<2||a<.55)return 1;if(s.seen<5||a<.82)return 2;return 3}
function coachLevelName(id){return ["","Разбираем с нуля","Закрепляем на примерах","Тренируем как на встрече"][coachLevel(id)]}
function coachPriority(t){const s=coachStat(t.id),a=coachAccuracy(t.id),weak=state.weak.includes(t.id)?8:0,due=(state.srs[t.id]&&state.srs[t.id].due<=today())?7:0,unseen=s.seen===0?12:0,recent=state.coachRecent.includes(t.id)?18:0;return unseen+weak+due+(s.wrong||0)*2+(s.seen?Math.round((1-a)*8):0)-Math.min(5,s.right||0)-recent}
function coachFocusTerms(){const p=coachPlan(),d=coachDay();if(state.coachPlan==="7")return (COACH_WEEK[(d-1)%7]||[]).map(term).filter(Boolean);const start=((d-1)*p.newPerDay)%TERMS.length,out=[];for(let i=0;i<Math.min(p.newPerDay,TERMS.length);i++)out.push(TERMS[(start+i)%TERMS.length]);return out}
function coachPool(){const preferred=[...dueTerms(),...state.weak.map(term).filter(Boolean),...coachFocusTerms()].filter(Boolean),seen=new Set(),out=[];const add=t=>{if(t&&!seen.has(t.id)){seen.add(t.id);out.push(t)}};for(const t of preferred.sort((a,b)=>coachPriority(b)-coachPriority(a)))if(!state.coachRecent.includes(t.id))add(t);for(const t of TERMS.slice().sort((a,b)=>coachPriority(b)-coachPriority(a)))if(!state.coachRecent.includes(t.id))add(t);for(const t of preferred.sort((a,b)=>coachPriority(b)-coachPriority(a)))add(t);for(const t of TERMS.slice().sort((a,b)=>coachPriority(b)-coachPriority(a)))add(t);return out}
function coachDecoys(correct,count=2){const same=TERMS.filter(t=>t.id!==correct.id&&t.cat===correct.cat),pool=[...same,...TERMS.filter(t=>t.id!==correct.id&&!same.some(x=>x.id===t.id))],out=[];for(const t of pool){if(out.length>=count)break;if(!out.some(x=>x.id===t.id))out.push(t)}return out}
function coachShuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function coachChoices(t,field){const options=coachShuffle([t,...coachDecoys(t,2)]);return {options:options.map(x=>field(x)),answer:options.findIndex(x=>x.id===t.id)}}
function coachOptionTask(type,t,prompt,values,answer){return {type,termId:t.id,prompt,options:values,answer,answered:false,selected:-1}}
function buildCoachTasks(t){const g=coachGuide(t),level=coachLevel(t.id),dec=coachDecoys(t,2),tasks=[];
 if(coachStat(t.id).seen===0)tasks.push({type:"lesson",termId:t.id});
 const meaning=coachShuffle([t.simple,dec[0]?.simple||"Другое понятие",dec[1]?.simple||"Другое понятие"]);
 if(level<=1)tasks.push(coachOptionTask("meaning",t,`Как точнее всего объяснить «${t.word}» простыми словами?`,meaning,meaning.indexOf(t.simple)));
 const scenario=coachChoices(t,x=>x.word);tasks.push(coachOptionTask("scenario",t,`Ситуация: ${t.example||t.simple} Какой термин здесь нужен?`,scenario.options,scenario.answer));
 const purpose=coachShuffle([g.investorGoal,coachGuide(dec[0]).investorGoal,coachGuide(dec[1]).investorGoal]);tasks.push(coachOptionTask("investor",t,`Инвестор спрашивает: «${t.investor||`Что показывает ${t.word}?`}» Что он пытается понять?`,purpose,purpose.indexOf(g.investorGoal)));
 if(level>=2){const usage=coachShuffle([g.use,coachGuide(dec[0]).use,coachGuide(dec[1]).use]);tasks.push(coachOptionTask("usage",t,`Где «${t.word}» используется наиболее уместно?`,usage,usage.indexOf(g.use)))}
 const responses=coachShuffle([g.best,coachGuide(dec[0]).best,coachGuide(dec[1]).best]);tasks.push(coachOptionTask("response",t,`Какой ответ на вопрос про «${t.word}» звучит профессиональнее?`,responses,responses.indexOf(g.best)));
 tasks.push({type:"speech",termId:t.id,prompt:`Ответьте голосом 20–40 секунд. Инвестор спрашивает: «${t.investor||`Объясните ${t.word} применительно к вашему бизнесу.`}»`,answered:false,score:null,feedback:""});
 return tasks}
function startCoach(count=2){const chosen=coachPool().slice(0,Math.max(1,Math.min(2,count))),groups=chosen.map(buildCoachTasks),tasks=[],max=Math.max(...groups.map(g=>g.length));for(let step=0;step<max;step++)for(const group of groups)if(group[step])tasks.push(group[step]);coachSession={count:chosen.length,index:0,tasks,terms:chosen.map(t=>t.id),plan:state.coachPlan,day:coachDay(),answered:0,correct:0,mistakes:[]};state.coachRecent=[...state.coachRecent,...chosen.map(t=>t.id)].slice(-12);voiceBuffers.coach="";save();renderCoach();pushAppHistory("coach",{coachSession:true,coachIndex:0})}
function coachRecordResult(task,ok){const s=coachStat(task.termId);s.seen=(s.seen||0)+1;s.last=today();coachSession.answered=(coachSession.answered||0)+1;if(ok){s.right=(s.right||0)+1;s.streak=(s.streak||0)+1;coachSession.correct=(coachSession.correct||0)+1}else{s.wrong=(s.wrong||0)+1;s.streak=0;if(!coachSession.mistakes.includes(task.termId))coachSession.mistakes.push(task.termId)}updateSRS(task.termId,ok)}
function coachAnswer(i){const task=coachSession?.tasks?.[coachSession.index];if(!task||["lesson","speech"].includes(task.type)||task.answered)return;task.selected=i;task.answered=true;coachRecordResult(task,i===task.answer);save();renderCoach();renderDashboard()}
function coachNext(){if(!coachSession)return;const task=coachSession.tasks[coachSession.index];if(task.type!=="lesson"&&!task.answered)return;if(task.type==="lesson"){const s=coachStat(task.termId);s.seen=(s.seen||0)+1;s.last=today();save()}coachSession.index++;voiceBuffers.coach="";renderCoach();pushAppHistory("coach",{coachSession:true,coachIndex:coachSession.index})}
function coachBack(){if(history.state?.view==='coach'&&window.history.length>1){history.back();return}if(coachSession&&coachSession.index>0){coachSession.index--;voiceBuffers.coach="";renderCoach()}else{coachSession=null;renderCoach()}}
function coachNextDay(){const p=coachPlan(),d=coachDay();state.coachPlanDays[state.coachPlan]=d>=p.days?1:d+1;save();coachSession=null;renderCoach();renderDashboard();pushAppHistory("coach",{coachSession:false})}
function coachSpeechLocal(text,t){const low=(text||"").toLowerCase(),source=`${t.word} ${t.simple} ${t.why||""} ${t.investor||""}`.toLowerCase().replace(/[(),—]/g," "),keywords=[...new Set(source.split(/\s+/).filter(x=>x.length>5))],hits=keywords.filter(k=>low.includes(k)).length;let score=35+Math.min(35,hits*7)+(low.length>120?15:low.length>60?8:0)+(/\d/.test(low)?8:0);score=Math.min(100,score);return {score,feedback:score>=82?"Сильный ответ: смысл понятен и звучит применимо.":score>=68?"Смысл есть. Добавьте конкретику: цифру, период, сегмент или пример из бизнеса.":"Ответ пока слишком общий. Скажите: что означает термин → зачем инвестору → один конкретный пример."}}
function coachTaskComment(task,t){const g=coachGuide(t);if(task.type==="meaning")return `Коротко: ${t.simple}`;if(task.type==="scenario")return `Это проверка применения: термин должен работать в реальной ситуации, а не только в определении.`;if(task.type==="investor")return `Инвестор проверяет: ${g.investorGoal}`;if(task.type==="usage")return `Рабочий контекст: ${g.use}`;if(task.type==="response")return `Профессиональный ответ строится как тезис → конкретика → доказательство. ${g.best}`;return t.simple}
function coachFeedback(task,t){const ok=task.selected===task.answer;return `<div class="answer-result ${ok?'is-correct':'is-wrong'}"><strong>${ok?'Правильно':'Неправильно'}</strong></div>${!ok?`<div class="answer-line wrong-line"><span>Ваш ответ</span><strong>${safe(task.options[task.selected])}</strong></div>`:''}<div class="answer-line correct-line"><span>Правильный ответ</span><strong>${safe(task.options[task.answer])}</strong></div><div class="feedback lesson-feedback"><p><strong>Комментарий:</strong> ${safe(coachTaskComment(task,t))}</p></div>`}
function coachPlanTabs(){return `<div class="filterbar coach-plan-tabs">${Object.entries(COACH_PLANS).map(([id,p])=>`<button class="${state.coachPlan===id?'active':''}" onclick="setCoachPlan('${id}')">${p.label}</button>`).join('')}</div>`}
function coachBackButton(){return `<button class="btn secondary coach-back" onclick="coachBack()">← Назад</button>`}
function renderCoach(){const root=$("#view-coach");if(!root)return;const p=coachPlan(),d=coachDay();if(!coachSession){const focus=coachFocusTerms().slice(0,6).map(t=>t.word).join(" · "),weak=TERMS.filter(t=>state.weak.includes(t.id)).length;root.innerHTML=`<div class="card"><div class="row between"><div><span class="tag">ГЛАВНЫЙ РЕЖИМ</span><h2>Coach</h2><p class="muted">Понимание → ситуация → логика инвестора → сильный ответ → живая речь.</p></div><div class="score-ring" style="--score:${mastery()}"><span>${mastery()}%</span></div></div>${coachPlanTabs()}<div class="grid grid-2"><div><strong>${p.title}</strong><p class="muted">${p.desc}</p><small>${p.pace} · день ${d} из ${p.days}</small></div><div><strong>Сегодня</strong><p class="muted">${focus||"Адаптивный набор терминов"}</p><small>Слабых тем: ${weak}</small></div></div><div class="row"><button class="btn" onclick="startCoach(1)">Начать 1 термин</button><button class="btn" onclick="startCoach(2)">Начать 2 термина</button></div><p class="muted small">Coach не повторяет один и тот же разбор подряд. Ошибки возвращаются позже и в другом контексте.</p></div>`;return}
 if(coachSession.index>=coachSession.tasks.length){const score=pct(coachSession.correct,coachSession.answered),names=coachSession.terms.map(id=>term(id)?.word).filter(Boolean).join(" · ");root.innerHTML=`<div class="card"><span class="tag">ПОДХОД ЗАВЕРШЁН</span><h2>${score}%</h2><p><strong>${safe(names)}</strong></p><p class="muted">Следующий подход даст другие термины. Ошибки вернутся позже по интервальному повторению, а не на соседнем экране.</p><div class="row">${coachBackButton()}<button class="btn" onclick="coachSession=null;renderCoach()">Новый подход</button><button class="btn secondary" onclick="coachNextDay()">Следующий день</button></div></div>`;return}
 const task=coachSession.tasks[coachSession.index],t=term(task.termId),g=coachGuide(t),n=coachSession.index+1,total=coachSession.tasks.length,level=coachLevelName(t.id);
 if(task.type==="lesson"){root.innerHTML=`<div class="quiz"><div class="row between">${coachBackButton()}<span class="tag">COACH · ${n}/${total}</span></div><div class="card quiz-card"><div class="row between"><div><span class="tag">${safe(t.cat)}</span><h2>${safe(t.word)}</h2></div><span class="muted small">${safe(level)}</span></div><p class="definition"><strong>Просто:</strong> ${safe(t.simple)}</p><p><strong>Зачем это нужно:</strong> ${safe(g.purpose)}</p><p><strong>Пример:</strong> ${safe(t.example||"Пример зависит от бизнеса.")}</p><p><strong>Что хочет понять инвестор:</strong> ${safe(g.investorGoal)}</p>${t.formula?`<p><strong>Формула:</strong> ${safe(t.formula)}</p>`:""}<button class="btn feedback-next" onclick="coachNext()">Проверить на практике</button></div></div>`;return}
 if(task.type==="speech"){root.innerHTML=`<div class="quiz"><div class="row between">${coachBackButton()}<span class="tag">COACH · ${n}/${total}</span></div><div class="card quiz-card"><span class="tag">ЖИВАЯ РЕЧЬ</span><h2>${safe(task.prompt)}</h2><p class="muted">Не читайте определение. Ответьте как на встрече: коротко, своими словами, с одним конкретным примером или цифрой.</p>${voicePanel('coach')}<div id="coachSpeechResult">${task.feedback||""}</div>${task.answered?`<button class="btn feedback-next" onclick="coachNext()">Следующий шаг</button>`:""}</div></div>`;restoreVoiceTranscript('coach');return}
 const labels={meaning:"Смысл",scenario:"Применение",investor:"Логика инвестора",usage:"Где употребляется",response:"Ответ на встрече"};root.innerHTML=`<div class="quiz"><div class="row between">${coachBackButton()}<span class="muted small">${safe(level)}</span></div><div class="row between"><span class="tag">COACH · ${n}/${total}</span><span class="muted small">${labels[task.type]||"Практика"}</span></div><div class="card quiz-card"><h2>${safe(task.prompt)}</h2><div>${task.options.map((o,i)=>`<button class="option ${task.answered?(i===task.answer?'correct':i===task.selected?'wrong':''):''}" ${task.answered?'disabled':''} onclick="coachAnswer(${i})">${safe(o)}</button>`).join("")}</div>${task.answered?`${coachFeedback(task,t)}<button class="btn feedback-next" onclick="coachNext()">Следующий шаг</button>`:""}</div></div>`}


let quizIndex=0,quizAnswered=false,lastAnswer=-1,currentQuiz=null;
function buildQuizQueue(){const dueIds=new Set(dueTerms().map(t=>t.id));const weakIds=new Set(state.weak);return [...QUIZ].sort((a,b)=>(dueIds.has(b.termId)?3:0)+(weakIds.has(b.termId)?2:0)-((dueIds.has(a.termId)?3:0)+(weakIds.has(a.termId)?2:0)))}
function getQuiz(){const q=buildQuizQueue();return q[quizIndex%q.length]}
function quizFeedback(q){const t=term(q.termId);const ok=lastAnswer===q.a;return `<div class="answer-result ${ok?'is-correct':'is-wrong'}"><strong>${ok?'Правильно':'Неправильно'}</strong></div>${!ok?`<div class="answer-line wrong-line"><span>Ваш ответ</span><strong>${safe(q.options[lastAnswer])}</strong></div>`:''}<div class="answer-line correct-line"><span>Правильный ответ</span><strong>${safe(q.options[q.a])}</strong></div><div class="feedback lesson-feedback"><p><strong>Просто:</strong> ${safe(t?.simple||q.why)}</p><p><strong>Почему:</strong> ${safe(q.why)}</p>${t?.example?`<p><strong>Пример:</strong> ${safe(t.example)}</p>`:''}<p><strong>Где используется:</strong> ${safe(termUse(t))}</p></div>`}
function renderTrain(){if(!currentQuiz)currentQuiz=getQuiz();const q=currentQuiz;$("#view-train").innerHTML=`<div class="quiz"><div class="row between"><span class="tag">ВОПРОС ${quizIndex+1}</span><span class="muted small">Выберите один ответ</span></div><div class="card quiz-card"><h2>${q.q}</h2><div>${q.options.map((o,i)=>`<button class="option ${quizAnswered?(i===q.a?'correct':i===lastAnswer?'wrong':''):''}" ${quizAnswered?'disabled':''} onclick="answerQuiz(${i})">${o}</button>`).join("")}</div>${quizAnswered?`${quizFeedback(q)}<button class="btn feedback-next" onclick="nextQuiz()">Следующий вопрос</button>`:""}</div></div>`}
function answerQuiz(i){if(quizAnswered)return;const q=currentQuiz||getQuiz();currentQuiz=q;lastAnswer=i;quizAnswered=true;state.total++;const ok=i===q.a;if(ok)state.correct++;updateSRS(q.termId,ok);setDaily('review');save();renderTrain();renderDashboard()}
function nextQuiz(){if(!quizAnswered)return;quizIndex++;quizAnswered=false;lastAnswer=-1;currentQuiz=null;renderTrain()}

let speakTerm=TERMS[0];
function chooseSpeakTerm(){const candidates=[...dueTerms(),...state.weak.map(term).filter(Boolean)];speakTerm=candidates[0]||TERMS[Math.floor(Math.random()*TERMS.length)]}
function renderSpeak(){if(!speakTerm)chooseSpeakTerm();$("#view-speak").innerHTML=`<div class="grid grid-2"><div class="card voice-card"><span class="tag">ГОЛОСОВОЙ ACTIVE RECALL</span><h2>${speakTerm.word}</h2><p class="muted">${speakTerm.full}</p><h3>Объясните термин своими словами и приведите пример.</h3>${voicePanel('speak')}<div id="speakResult"></div><button class="btn secondary" onclick="newSpeakTerm()">Следующий термин</button></div><div class="card"><h3>После ответа сравните</h3><p><strong>Коротко:</strong> ${speakTerm.simple}</p>${speakTerm.formula?`<p><strong>Формула:</strong> ${speakTerm.formula}</p>`:""}<p><strong>Пример:</strong> ${speakTerm.example||'Сформулируйте собственный пример.'}</p><p><strong>Вопрос инвестора:</strong> ${speakTerm.investor}</p></div></div>`;restoreVoiceTranscript('speak')}
function newSpeakTerm(){chooseSpeakTerm();voiceBuffers.speak="";renderSpeak()}
function evaluateSpeak(text){const low=(text||"").toLowerCase();const base=(speakTerm.word+" "+speakTerm.full+" "+speakTerm.simple+" "+(speakTerm.why||"")).toLowerCase().replace(/[(),—]/g," ");const keywords=[...new Set(base.split(/\s+/).filter(x=>x.length>5))];const hits=keywords.filter(k=>low.includes(k)).length;const score=Math.min(100,25+hits*10+(low.length>100?20:0)+(/\d/.test(low)?10:0));updateSRS(speakTerm.id,score>=70);state.voiceScores.push(score);setDaily('voice');save();const el=$("#speakResult");if(el)el.innerHTML=`<div class="feedback"><strong>Оценка объяснения: ${score}/100</strong><p>${score>=80?'Хорошо: смысл воспроизводится из памяти.':score>=60?'Основа есть. Добавьте пример и связь с решением инвестора.':'Повторите термин через короткий интервал и попробуйте снова без подсказки.'}</p><p class="small"><strong>Эталон:</strong> ${speakTerm.simple}</p></div>`;renderDashboard()}

let pitchTopic="SaaS-стартап";const PITCH_LABELS={problem:"Проблема",solution:"Решение",market:"Рынок",traction:"Traction",model:"Модель",ask:"Запрос"};
function renderPitch(){const p=PITCH_TOPICS[pitchTopic]||Object.values(PITCH_TOPICS)[0];$("#view-pitch").innerHTML=`<div class="grid grid-2"><div class="card"><div class="row between"><div><span class="tag">ГОЛОСОВОЙ PITCH</span><h2>Рассказ о своём проекте</h2></div><select class="input pitch-select" onchange="pitchTopic=this.value;renderPitch()">${Object.keys(PITCH_TOPICS).map(x=>`<option ${x===pitchTopic?'selected':''}>${x}</option>`).join("")}</select></div><p class="muted">Структура — только опора. Сначала посмотрите, затем уберите подсказку и расскажите всё голосом одним заходом.</p><div class="grid">${Object.entries(p).map(([k,v])=>`<div class="card pitch-part"><strong>${PITCH_LABELS[k]||k}</strong><p class="muted">${v}</p></div>`).join("")}</div></div><div class="card voice-card"><h3>Запишите pitch голосом</h3><p class="muted">Нажмите «Начать». Говорите сколько нужно. Текст будет накапливаться. Нажмите «Отправить pitch» — запись остановится и только тогда ответ будет оценён.</p>${voicePanel('pitch')}<div id="pitchScore"></div><div class="small muted pitch-checklist">Проверка: проблема → решение → рынок → traction → бизнес-модель → конкуренция → команда → раунд → использование капитала.</div></div></div>`;restoreVoiceTranscript('pitch')}
function scorePitchText(text){const t=(text||"").toLowerCase();const groups=[["проблем","боль"],["решен","продукт"],["рын","tam","sam"],["traction","retention","mrr","выруч","рост"],["модел","saas","подпис"],["клиент","icp","сегмент"],["конкур","альтернатив"],["команд","основател","опыт"],["раунд","привлека","инвест"],["капитал","средств","runway","milestone"]];const present=groups.map(g=>g.some(k=>t.includes(k)));let score=Math.round(present.filter(Boolean).length/groups.length*85);if(t.length>400)score+=8;if(/\d/.test(t))score+=7;score=Math.min(100,score);state.pitchScores.push(score);state.voiceScores.push(score);save();const missing=["проблема","решение","рынок","traction/цифры","модель","ICP","конкуренция","команда","раунд","use of funds"].filter((_,i)=>!present[i]);const el=$("#pitchScore");if(el)el.innerHTML=`<div class="feedback"><strong>Оценка pitch: ${score}/100</strong><p>${score>=80?'Структура сильная. Теперь сокращайте лишнее и тренируйте ответы на вопросы.':score>=60?'Хорошая основа. Добавьте конкретные цифры и причинную связь.':'Pitch пока больше похож на описание продукта. Нужна инвестиционная логика.'}</p><p class="small"><strong>Не хватает:</strong> ${missing.join(', ')||'ключевые блоки найдены'}.</p></div>`;renderDashboard()}

const SIM=[
{q:"Расскажите о компании за одну минуту.",good:["проблем","решен","клиент","рын"],numbers:false,tip:"Проблема → для кого → решение → доказательство."},
{q:"Кто ваш первый узкий целевой клиент и почему именно он?",good:["сегмент","клиент","icp","боль"],numbers:false,tip:"Назовите конкретный сегмент, не «все»."},
{q:"Какие данные доказывают, что продукт нужен рынку?",good:["retention","выруч","mrr","клиент","рост","плат"],numbers:true,tip:"Скачивания слабее retention, активного использования и выручки."},
{q:"Какова ваша unit economics: CAC, LTV, gross margin и payback?",good:["cac","ltv","марж","payback","окуп"],numbers:true,tip:"Если метрики ещё неизвестны, честно назовите, что измеряете и к какой дате получите данные."},
{q:"Как вы будете масштабировать go-to-market без пропорционального роста затрат?",good:["gtm","канал","organic","plg","sales","cac","conversion"],numbers:false,tip:"Опишите повторяемый канал и economics."},
{q:"Кто ваши конкуренты и почему вы выиграете?",good:["конкур","альтернатив","moat","преимущ","position"],numbers:false,tip:"Никогда не отвечайте «конкурентов нет»."},
{q:"Сколько вы привлекаете, на сколько месяцев runway и какие milestones должны получить?",good:["раунд","привлека","runway","месяц","milestone","капитал"],numbers:true,tip:"Свяжите сумму с временем и измеримыми результатами."},
{q:"Назовите три главных риска и что вы делаете для их снижения.",good:["риск","если","сниз","провер","план"],numbers:false,tip:"Сильный основатель не отрицает риск, а управляет им."},
{q:"Почему именно ваша команда имеет право выиграть этот рынок?",good:["опыт","команд","insight","сеть","эксперт","traction"],numbers:false,tip:"Founder-market fit — конкретный опыт и уникальный insight."},
{q:"Почему сейчас правильный момент для этой компании?",good:["сейчас","рынок","технолог","регуля","поведен","измен"],numbers:false,tip:"Why Now должно опираться на изменение среды, а не на желание основателя."}
];
function renderInvestor(){const msgs=state.messages.length?state.messages:[{who:"ai",text:SIM[Math.min(state.simStep,SIM.length-1)].q}];$("#view-investor").innerHTML=`<div class="grid grid-2"><div class="card voice-card"><div class="row between"><div><span class="tag">ГОЛОСОВОЙ СИМУЛЯТОР</span><h2>Встреча с инвестором</h2></div><span class="muted small">${Math.min(state.simStep+1,SIM.length)}/${SIM.length}</span></div><div class="sim-chat" id="simChat">${msgs.map(m=>`<div class="bubble ${m.who}">${safe(m.text)}</div>`).join("")}</div><p class="muted">Ответьте голосом. Можно говорить долго: распознанный текст накапливается. Ответ уходит только после кнопки «Отправить ответ».</p>${voicePanel('sim')}<div class="row"><button class="btn secondary" onclick="resetSim()">Начать заново</button></div></div><div class="card"><h3>Что оценивает тренер</h3><p class="muted">Прямой ответ на вопрос, конкретика, цифры там, где они нужны, отсутствие red flags и понимание причинно-следственной связи.</p><div id="simFeedback"><div class="feedback">${state.simStep?'Следующий вопрос сложнее предыдущего.':'Начните коротко и конкретно.'}</div></div><h3>Red flags</h3><div>${["У нас нет конкурентов","Наш клиент — каждый","Скачивания = PMF","Нам нужен только маркетинг","Мы не знаем ключевые метрики"].map(x=>`<span class="tag red-flag">🚩 ${x}</span>`).join("")}</div></div></div>`;const chat=$("#simChat");if(chat)chat.scrollTop=chat.scrollHeight;restoreVoiceTranscript('sim')}
function evaluateSim(text){const step=Math.min(state.simStep,SIM.length-1),s=SIM[step],low=(text||"").toLowerCase();const hits=s.good.filter(k=>low.includes(k)).length;let score=40+Math.round(hits/Math.max(1,s.good.length)*45);if(s.numbers&&/\d/.test(low))score+=15;score=Math.min(100,score);state.messages.push({who:"you",text:text},{who:"ai",text:step+1<SIM.length?SIM[step+1].q:"Базовая встреча завершена. Повторите её позже: вопросы те же, но ответы должны стать короче, точнее и сильнее по цифрам."});state.simStep=Math.min(step+1,SIM.length);state.voiceScores.push(score);setDaily('sim');save();voiceBuffers.sim="";renderInvestor();setTimeout(()=>{const f=$("#simFeedback");if(f)f.innerHTML=`<div class="feedback"><strong>Оценка ответа: ${score}/100</strong><p>${score>=80?'Сильный ответ.':score>=60?'Смысл есть, но добавьте больше доказательств и точности.':'Ответ пока не закрывает инвесторский вопрос.'}</p><p class="small">${s.tip}</p></div>`},30);renderDashboard()}
function resetSim(){state.simStep=0;state.messages=[];voiceBuffers.sim="";save();renderInvestor()}

function renderRoadmap(){const mode=state.courseMode||"30";const arr=mode==="7"?WEEK_COURSE:COURSE;$("#view-roadmap").innerHTML=`<div class="card"><div class="row between roadmap-head"><div><span class="tag">УЧЕБНЫЙ ТРЕК</span><h2>${mode==='7'?'Интенсив за 7 дней':'Системный курс на 30 дней'}</h2><p class="muted">Курс не заменяет повторения: завершённый день не считается освоенным, пока слабые темы не прошли несколько успешных интервалов.</p></div><div class="course-switch"><button class="${mode==='7'?'active':''}" onclick="setCourseMode('7')">7 дней</button><button class="${mode==='30'?'active':''}" onclick="setCourseMode('30')">30 дней</button></div></div></div><div class="timeline roadmap-timeline">${arr.map((c,i)=>{const d=i+1,done=mode==='30'&&state.day>d;return `<div class="card day ${done?'done':''}"><div class="day-num">${done?'✓':'Д'+d}</div><div><h3>${c[0]}</h3><p>${c[1]}</p><div class="row"><button class="btn secondary" onclick="go('learn')">Термины</button><button class="btn secondary" onclick="go('train')">Тест</button>${d>=5?`<button class="btn secondary" onclick="go('investor')">Голосовая практика</button>`:''}</div></div></div>`}).join("")}</div>${mode==='30'?`<div class="card roadmap-rule"><h3>Завершение дня</h3><p class="muted">Завершайте день после активного повторения, а не после чтения. На следующий день приложение снова покажет то, что пора вспоминать.</p><button class="btn" onclick="advanceDay()">Завершить сегодняшний день</button></div>`:''}`}
function setCourseMode(m){state.courseMode=m;save();renderRoadmap()} function advanceDay(){if(state.day<30){state.day++;state.streak++;save();renderAll();toast("День завершён. Повторения уже запланированы.")}else toast("30-дневный курс завершён")}

// Voice capture: accumulated speech is only submitted when the user presses Send.
const voiceBuffers={speak:"",pitch:"",sim:"",coach:""};let recognition=null,voiceChannel=null,voiceRunning=false,voiceStoppingForSend=false;
function voicePanel(ch){return `<div class="voice-recorder" id="voice-${ch}"><div class="voice-status"><span class="rec-dot"></span><strong id="voiceStatus-${ch}">Готов к записи</strong><small>Распознавание речи выполняет браузер</small></div><div class="voice-transcript" id="voiceTranscript-${ch}">Ваш распознанный ответ появится здесь.</div><div class="row action-row"><button class="btn" id="voiceStart-${ch}" onclick="toggleVoice('${ch}')">🎙 Начать голосовой ответ</button><button class="btn send-voice" onclick="submitVoice('${ch}')">➤ Отправить</button></div></div>`}
function speechAvailable(){return 'SpeechRecognition' in window||'webkitSpeechRecognition' in window}
function restoreVoiceTranscript(ch){const el=$("#voiceTranscript-"+ch);if(el&&voiceBuffers[ch])el.textContent=voiceBuffers[ch]}
function setVoiceUI(ch,status,running){const st=$("#voiceStatus-"+ch),btn=$("#voiceStart-"+ch),wrap=$("#voice-"+ch);if(st)st.textContent=status;if(btn){btn.textContent=running?'● Запись идёт':'🎙 Начать запись';btn.disabled=!!running}if(wrap)wrap.classList.toggle('recording',running)}
function toggleVoice(ch){if(voiceRunning&&voiceChannel===ch){toast('Чтобы закончить запись, нажмите «Отправить».');return}startVoice(ch)}
function startVoice(ch){if(!speechAvailable()){toast("В этом браузере нет SpeechRecognition. Для голосовой тренировки используйте Chrome/Edge на Android/desktop или Safari с поддержкой распознавания речи.");return}if(voiceRunning)stopVoice(false);const R=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new R();recognition.lang='ru-RU';recognition.continuous=true;recognition.interimResults=true;voiceChannel=ch;voiceRunning=true;voiceStoppingForSend=false;let sessionFinal="";recognition.onstart=()=>setVoiceUI(ch,'Идёт запись…',true);recognition.onresult=e=>{let interim="";for(let i=e.resultIndex;i<e.results.length;i++){const tx=e.results[i][0].transcript;if(e.results[i].isFinal)sessionFinal+=(sessionFinal?' ':'')+tx;else interim+=tx}const base=[voiceBuffers[ch],sessionFinal].filter(Boolean).join(' ').trim();const el=$("#voiceTranscript-"+ch);if(el)el.textContent=(base+(interim?' '+interim:'')).trim()||'Слушаю…'};recognition.onerror=e=>{if(e.error!=='no-speech'&&e.error!=='aborted')toast('Ошибка распознавания: '+e.error)};recognition.onend=()=>{if(sessionFinal){voiceBuffers[ch]=[voiceBuffers[ch],sessionFinal].filter(Boolean).join(' ').trim();sessionFinal=""}restoreVoiceTranscript(ch);if(voiceRunning&&voiceChannel===ch&&!voiceStoppingForSend){try{recognition.start();return}catch(_){}}voiceRunning=false;setVoiceUI(ch,'Запись остановлена',false);if(voiceStoppingForSend){voiceStoppingForSend=false;finalSubmit(ch)}};try{recognition.start()}catch(e){voiceRunning=false;toast('Не удалось запустить микрофон')}}
function stopVoice(forSend){if(!voiceRunning||!recognition){if(forSend)finalSubmit(voiceChannel);return}voiceStoppingForSend=forSend;voiceRunning=false;try{recognition.stop()}catch(_){if(forSend)finalSubmit(voiceChannel)}}
function submitVoice(ch){voiceChannel=ch;if(voiceRunning&&voiceChannel===ch){voiceStoppingForSend=true;voiceRunning=false;try{recognition.stop()}catch(_){finalSubmit(ch)}}else finalSubmit(ch)}
function finalSubmit(ch){const text=(voiceBuffers[ch]||"").trim();if(!text){toast("Сначала запишите голосовой ответ.");return}setVoiceUI(ch,'Ответ отправлен',false);if(ch==='speak')evaluateSpeak(text);if(ch==='pitch')scorePitchText(text);if(ch==='sim')evaluateSim(text)}

const views={dashboard:"Главная",learn:"Изучение",coach:"Coach",train:"Тесты",speak:"Живая речь",pitch:"Pitch",investor:"Симуляция инвестора",roadmap:"Курс"};
let currentView="dashboard",historyReady=false;
function pushAppHistory(view,extra={}){if(!historyReady)return;const next={view,...extra},cur=history.state||{};if(cur.view===next.view&&cur.coachSession===next.coachSession&&cur.coachIndex===next.coachIndex)return;history.pushState(next,"",location.href)}
function go(v,opts={}){if(voiceRunning){if(typeof cancelVoiceCapture==='function')cancelVoiceCapture();else stopVoice(false);}$$('.view').forEach(x=>x.classList.remove('active'));const target=$("#view-"+v);if(target)target.classList.add('active');$$('.nav-item,.bottom-nav-item').forEach(x=>{const active=x.dataset.view===v;x.classList.toggle('active',active);if(active)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')});const title=$("#pageTitle");if(title)title.textContent=views[v]||v;currentView=v;renderView(v);if(opts.focus!==false&&target)try{target.focus({preventScroll:true})}catch{}window.scrollTo({top:0,behavior:opts.history===false?'auto':'smooth'});const sb=$('.sidebar');if(sb)sb.classList.remove('open');if(mm)mm.setAttribute('aria-expanded','false');if(opts.history!==false)pushAppHistory(v,{coachSession:v==='coach'?!!coachSession:false,coachIndex:v==='coach'&&coachSession?coachSession.index:null})}
function restoreHistoryState(st){const target=st?.view||"dashboard";if(target==='coach'){if(st.coachSession===false)coachSession=null;else if(coachSession&&Number.isInteger(st.coachIndex))coachSession.index=Math.max(0,Math.min(st.coachIndex,coachSession.tasks.length));go('coach',{history:false});return}go(target,{history:false})}
window.addEventListener('popstate',e=>restoreHistoryState(e.state));
function renderView(v){({dashboard:renderDashboard,learn:renderLearn,coach:renderCoach,train:renderTrain,speak:renderSpeak,pitch:renderPitch,investor:renderInvestor,roadmap:renderRoadmap})[v]?.()}
function renderAll(){renderDashboard();renderLearn();renderCoach();renderTrain();renderSpeak();renderPitch();renderInvestor();renderRoadmap();$("#streak").textContent=state.streak;$("#dayLabel").textContent=`День ${state.day} из 30`;$("#sideProgress").style.width=(state.day/30*100)+'%'}
const mm=$("#mobileMenu");$$('.nav-item,.bottom-nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));if(mm){mm.setAttribute('aria-expanded','false');mm.addEventListener('click',()=>{const sb=$('.sidebar'),open=!sb.classList.contains('open');sb.classList.toggle('open',open);mm.setAttribute('aria-expanded',String(open))})}renderAll();history.replaceState({view:'dashboard',coachSession:false,coachIndex:null},'',location.href);historyReady=true;

// PWA installation/update logic kept intact and update checks remain network-first.
let deferredInstallPrompt=null;const isStandalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
function setInstallState(){const b=$("#installApp"),t=$("#installState");if(!b||!t)return;if(isStandalone()){b.hidden=true;t.hidden=false;t.textContent='Приложение установлено'}else{t.hidden=true;b.hidden=false;b.textContent='Установить приложение'}}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;setInstallState()});addEventListener('appinstalled',()=>{deferredInstallPrompt=null;setInstallState();toast('Приложение установлено')});
async function installApp(){if(isStandalone()){setInstallState();return}if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;setInstallState();return}openInstallHelp()}
let installModalReturnFocus=null;function openInstallHelp(){installModalReturnFocus=document.activeElement;const m=$("#installModal"),body=$("#installHelpText");if(isIOS())body.innerHTML='<strong>iPhone / iPad:</strong><br>1. Откройте сайт в Safari.<br>2. Нажмите <strong>«Поделиться»</strong>.<br>3. Выберите <strong>«На экран „Домой“»</strong>.<br>4. Подтвердите добавление.';else body.innerHTML='<strong>Android:</strong><br>Откройте меню браузера и выберите <strong>«Установить приложение»</strong> или используйте системную кнопку установки.';m.hidden=false;document.body.classList.add('modal-open');setTimeout(()=>$("#installClose")?.focus(),0)}
function closeInstallHelp(){$("#installModal").hidden=true;document.body.classList.remove('modal-open');if(installModalReturnFocus&&typeof installModalReturnFocus.focus==='function')installModalReturnFocus.focus();installModalReturnFocus=null}$("#installApp")?.addEventListener('click',installApp);$("#installClose")?.addEventListener('click',closeInstallHelp);$("#installModal")?.addEventListener('click',e=>{if(e.target.id==='installModal')closeInstallHelp()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$("#installModal")?.hidden)closeInstallHelp()});setInstallState();
if('serviceWorker' in navigator)addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await reg.update();let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()});reg.addEventListener('updatefound',()=>{const w=reg.installing;if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)w.postMessage({type:'SKIP_WAITING'})})})}catch(err){console.error('Service Worker:',err)}});


/* ===== Production learning engine + AI Investor v5 ===== */
state.aiMemory=state.aiMemory||"";
state.aiHistory=state.aiHistory||[];
state.aiWeakTopics=state.aiWeakTopics||[];
state.aiScores=state.aiScores||[];
state.projectProfile=state.projectProfile||{};
state.sessionPlan=state.sessionPlan||{};

function apiBase(){return (localStorage.getItem('investorCoachApiBase')||(window.INVESTOR_COACH_CONFIG&&window.INVESTOR_COACH_CONFIG.apiBase)||'').replace(/\/$/,'')}
function aiReady(){return /^https:\/\//.test(apiBase())}
function saveApiBase(){const el=document.querySelector('#aiApiBase');if(!el)return;const v=el.value.trim().replace(/\/$/,'');if(v&&!/^https:\/\//.test(v)){toast('Нужен HTTPS URL AI-backend.');return}localStorage.setItem('investorCoachApiBase',v);toast(v?'AI-backend сохранён.':'AI-backend отключён.');renderAll()}
function aiStatusHtml(){return aiReady()?'<span class="ai-pill online">● AI подключён</span>':'<span class="ai-pill offline">● Локальный режим</span>'}
function priorityScore(t){const s=srsInfo(t.id),now=new Date(today()+'T12:00:00'),due=new Date((s.due||today())+'T12:00:00');const overdue=Math.max(0,Math.round((now-due)/86400000));const attempts=(s.right||0)+(s.wrong||0);const errorRate=attempts?(s.wrong||0)/attempts:.45;const novelty=attempts?0:1;const weak=state.weak.includes(t.id)?2:0;const aiWeak=state.aiWeakTopics.some(x=>(t.word+' '+t.cat+' '+t.full).toLowerCase().includes(String(x).toLowerCase()))?1.5:0;return overdue*1.6+errorRate*4+novelty*2+weak+aiWeak-(s.box||0)*.7}
buildQuizQueue=function(){return [...QUIZ].sort((a,b)=>priorityScore(term(b.termId)||TERMS[0])-priorityScore(term(a.termId)||TERMS[0]))}
chooseSpeakTerm=function(){speakTerm=[...TERMS].sort((a,b)=>priorityScore(b)-priorityScore(a))[0]||TERMS[0]}
function readinessScore(){const knowledge=mastery();const voice=state.aiScores.length?Math.round(state.aiScores.slice(-10).reduce((a,b)=>a+b,0)/Math.min(10,state.aiScores.length)):(state.voiceScores.length?Math.round(state.voiceScores.slice(-10).reduce((a,b)=>a+b,0)/Math.min(10,state.voiceScores.length)):0);const tests=pct(state.correct,state.total);return Math.round(knowledge*.4+tests*.25+voice*.35)}
function todayPlan(){const due=dueTerms().slice(0,8).map(t=>t.word);const weak=[...TERMS].sort((a,b)=>priorityScore(b)-priorityScore(a)).slice(0,3).map(t=>t.word);return {review:due,newCount:Math.min(4,Math.max(1,8-due.length)),voice:weak[0]||'CAC',investor:state.aiWeakTopics[0]||weak[1]||'unit economics'} }
const _renderDashboardProd=renderDashboard;
renderDashboard=function(){_renderDashboardProd()}

async function aiCoach(mode,text,extra={}){if(!aiReady())throw new Error('AI_NOT_CONFIGURED');const payload={mode,transcript:text,memory:state.aiMemory,history:state.aiHistory.slice(-12),weak_topics:state.aiWeakTopics.slice(0,12),course_day:state.day,project_profile:state.projectProfile,context:extra};const r=await fetch(apiBase()+'/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const e=await r.text();throw new Error('AI '+r.status+': '+e.slice(0,180))}return r.json()}
function applyAiResult(res,mode,userText){const score=Math.max(0,Math.min(100,Number(res.score)||0));state.aiScores.push(score);state.voiceScores.push(score);state.aiMemory=String(res.memory_summary||state.aiMemory||'').slice(0,6000);state.aiWeakTopics=[...new Set([...(res.focus_topics||[]),...state.aiWeakTopics])].slice(0,20);state.aiHistory.push({role:'user',text:userText.slice(0,5000)},{role:'investor',text:String(res.next_question||res.verdict||'').slice(0,1500)});state.aiHistory=state.aiHistory.slice(-30);save();return score}
function feedbackHtml(res){return `<div class="feedback ai-feedback"><div class="row between"><strong>AI-оценка: ${safe(res.score)}/100</strong><span class="tag">production AI</span></div><p>${safe(res.verdict)}</p>${(res.strengths||[]).length?`<p><strong>Сильные стороны:</strong> ${(res.strengths||[]).map(safe).join(' • ')}</p>`:''}${(res.improvements||[]).length?`<p><strong>Исправить:</strong> ${(res.improvements||[]).map(safe).join(' • ')}</p>`:''}${(res.red_flags||[]).length?`<p><strong>Red flags:</strong> ${(res.red_flags||[]).map(safe).join(' • ')}</p>`:''}${res.model_answer?`<details><summary>Показать сильный вариант ответа</summary><p>${safe(res.model_answer)}</p></details>`:''}</div>`}

const _renderPitchProd=renderPitch;
renderPitch=function(){_renderPitchProd();const card=document.querySelector('#view-pitch .voice-card');if(card){const badge=document.createElement('div');badge.className='ai-mode-line';badge.innerHTML=`${aiStatusHtml()} <span class="small muted">При AI-режиме оценивается смысл, логика, цифры, investor narrative и риски.</span>`;card.prepend(badge)}}
renderInvestor=function(){const msgs=state.messages.length?state.messages:[{who:'ai',text:(state.aiHistory.slice().reverse().find(x=>x.role==='investor')||{}).text||SIM[Math.min(state.simStep,SIM.length-1)].q}];document.querySelector('#view-investor').innerHTML=`<div class="grid grid-2"><div class="card voice-card"><div class="row between"><div><span class="tag">PRODUCTION AI INVESTOR</span><h2>Голосовая встреча с инвестором</h2></div>${aiStatusHtml()}</div><div class="sim-chat" id="simChat">${msgs.map(m=>`<div class="bubble ${m.who}">${safe(m.text)}</div>`).join('')}</div><p class="muted">Нажмите запись, говорите как на реальной встрече и только затем нажмите «Отправить». В AI-режиме вопрос формируется из вашего предыдущего ответа и слабых мест, а не идёт по фиксированному скрипту.</p>${voicePanel('sim')}<div class="row"><button class="btn secondary" onclick="resetSim()">Новая встреча</button></div></div><div class="card"><h3>AI-память и адаптация</h3><p class="muted">Инвестор помнит факты вашего проекта, замечает противоречия и возвращается к слабым темам.</p><div id="simFeedback"><div class="feedback">${state.aiMemory?safe(state.aiMemory):'Память проекта сформируется после первых ответов.'}</div></div>${!aiReady()?`<div class="ai-connect"><h3>Подключить production AI</h3><p class="small muted">GitHub Pages не хранит секретные API-ключи. Разверните backend из папки <code>backend</code> и вставьте его HTTPS URL один раз.</p><input id="aiApiBase" class="input" placeholder="https://investor-coach-ai.YOUR.workers.dev" value="${safe(apiBase())}"><button class="btn" onclick="saveApiBase()">Сохранить AI URL</button></div>`:''}</div></div>`;const chat=document.querySelector('#simChat');if(chat)chat.scrollTop=chat.scrollHeight;restoreVoiceTranscript('sim')}

async function evaluateWithAI(ch,text){const status=document.querySelector('#voiceStatus-'+ch);if(status)status.textContent='AI анализирует ответ…';try{let extra={};if(ch==='speak')extra={term:{word:speakTerm.word,definition:speakTerm.simple,example:speakTerm.example,investor:speakTerm.investor}};else if(ch==='pitch')extra={pitch_topic:pitchTopic};else if(ch==='coach'){const task=coachSession?.tasks?.[coachSession.index],t=task?term(task.termId):null;extra={training_mode:"coach_speech",term:t?{word:t.word,definition:t.simple,example:t.example,investor:t.investor,why:t.why}:null,prompt:task?.prompt||""}}
 const res=await aiCoach(ch,text,extra),score=applyAiResult(res,ch,text);
 if(ch==='speak'){updateSRS(speakTerm.id,score>=75);setDaily('voice');const el=document.querySelector('#speakResult');if(el)el.innerHTML=feedbackHtml(res)}
 else if(ch==='pitch'){state.pitchScores.push(score);const el=document.querySelector('#pitchScore');if(el)el.innerHTML=feedbackHtml(res)}
 else if(ch==='sim'){state.messages.push({who:'you',text},{who:'ai',text:res.next_question||'Продолжайте.'});setDaily('sim');voiceBuffers.sim='';renderInvestor();setTimeout(()=>{const f=document.querySelector('#simFeedback');if(f)f.innerHTML=feedbackHtml(res)},20)}
 else if(ch==='coach'){const task=coachSession?.tasks?.[coachSession.index];if(task&&task.type==='speech'&&!task.answered){task.answered=true;task.score=score;task.feedback=feedbackHtml(res);coachRecordResult(task,score>=75);voiceBuffers.coach="";save();renderCoach();renderDashboard()}}
 save();renderDashboard();if(status)status.textContent='Ответ оценён'}catch(e){console.error(e);toast(e.message==='AI_NOT_CONFIGURED'?'AI не подключён — использую локальную оценку.':'AI временно недоступен — использую локальную оценку.');if(ch==='speak')evaluateSpeak(text);if(ch==='pitch')scorePitchText(text);if(ch==='sim')evaluateSim(text);if(ch==='coach')evaluateCoachSpeechLocal(text)}}
function evaluateCoachSpeechLocal(text){const task=coachSession?.tasks?.[coachSession.index];if(!task||task.type!=="speech"||task.answered)return;const t=term(task.termId),r=coachSpeechLocal(text,t);task.answered=true;task.score=r.score;task.feedback=`<div class="feedback"><strong>Оценка речи: ${r.score}/100</strong><p>${safe(r.feedback)}</p><p class="small"><strong>Сильный ориентир:</strong> ${safe(coachGuide(t).best)}</p></div>`;coachRecordResult(task,r.score>=70);voiceBuffers.coach="";save();renderCoach();renderDashboard()}


// Real recorder: audio is kept locally until Send, then transcribed server-side.
const mediaState={recorder:null,stream:null,ch:null,chunks:[],startedAt:0};
function cancelVoiceCapture(){try{if(mediaState.recorder&&(mediaState.recorder.state==='recording'||mediaState.recorder.state==='paused'))mediaState.recorder.stop()}catch(_){}try{mediaState.stream?.getTracks().forEach(t=>t.stop())}catch(_){}mediaState.recorder=null;mediaState.stream=null;mediaState.ch=null;mediaState.chunks=[];voiceRunning=false;if(recognition){try{recognition.abort()}catch(_){}}}
function canMediaRecord(){return !!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&window.MediaRecorder)}
voicePanel=function(ch){return `<div class="voice-recorder" id="voice-${ch}"><div class="voice-status"><span class="rec-dot"></span><strong id="voiceStatus-${ch}">Готов к записи</strong><small>${aiReady()?'Запись хранится локально и отправляется только после кнопки «Отправить»':'Для точной расшифровки подключите production AI'}</small></div><div class="voice-transcript" id="voiceTranscript-${ch}">${voiceBuffers[ch]||'Во время записи можно говорить свободно. Текст появится после отправки.'}</div><div class="row action-row"><button class="btn" id="voiceStart-${ch}" onclick="toggleVoice('${ch}')">🎙 Начать запись</button><button class="btn send-voice" onclick="submitVoice('${ch}')">➤ Отправить</button></div></div>`}
async function startMediaVoice(ch){if(mediaState.recorder&&mediaState.recorder.state==='recording')return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});let mime='';for(const t of ['audio/webm;codecs=opus','audio/mp4','audio/webm']){if(MediaRecorder.isTypeSupported(t)){mime=t;break}}const rec=new MediaRecorder(stream,mime?{mimeType:mime,audioBitsPerSecond:48000}:{audioBitsPerSecond:48000});mediaState.recorder=rec;mediaState.stream=stream;mediaState.ch=ch;mediaState.chunks=[];mediaState.startedAt=Date.now();voiceChannel=ch;voiceRunning=true;rec.ondataavailable=e=>{if(e.data&&e.data.size)mediaState.chunks.push(e.data)};rec.onstop=()=>{voiceRunning=false;setVoiceUI(ch,'Запись готова к отправке',false);stream.getTracks().forEach(t=>t.stop())};rec.start(1000);setVoiceUI(ch,'Идёт запись…',true);const el=document.querySelector('#voiceTranscript-'+ch);if(el)el.textContent='● Запись идёт. Нажмите «Отправить», когда закончите.'}catch(e){console.error(e);toast('Нет доступа к микрофону.');}}
toggleVoice=async function(ch){if(aiReady()&&canMediaRecord()){if(mediaState.recorder&&mediaState.ch===ch&&(mediaState.recorder.state==='recording'||mediaState.recorder.state==='paused')){toast('Чтобы закончить запись, нажмите «Отправить».');return}await startMediaVoice(ch);return}if(voiceRunning&&voiceChannel===ch){toast('Чтобы закончить запись, нажмите «Отправить».');return}startVoice(ch)}
async function transcribeBlob(blob){const fd=new FormData();const ext=blob.type.includes('mp4')?'m4a':'webm';fd.append('file',blob,'answer.'+ext);fd.append('language','ru');const r=await fetch(apiBase()+'/api/transcribe',{method:'POST',body:fd});if(!r.ok)throw new Error('TRANSCRIBE_'+r.status);const j=await r.json();return (j.text||'').trim()}
submitVoice=async function(ch){voiceChannel=ch;if(aiReady()&&mediaState.recorder&&mediaState.ch===ch&&(mediaState.recorder.state==='recording'||mediaState.recorder.state==='paused')){const rec=mediaState.recorder;const done=new Promise(resolve=>rec.addEventListener('stop',resolve,{once:true}));if(rec.state==='paused')rec.resume();rec.stop();await done;const blob=new Blob(mediaState.chunks,{type:rec.mimeType||'audio/webm'});if(blob.size<1000){toast('Запись слишком короткая.');return}setVoiceUI(ch,'Распознаю запись…',false);try{const text=await transcribeBlob(blob);voiceBuffers[ch]=text;const el=document.querySelector('#voiceTranscript-'+ch);if(el)el.textContent=text||'Речь не распознана.';if(!text){toast('Не удалось распознать речь.');return}await evaluateWithAI(ch,text)}catch(e){console.error(e);toast('Не удалось отправить аудио. Проверьте AI-backend.')}finally{mediaState.recorder=null;mediaState.chunks=[]}return}if(voiceRunning&&voiceChannel===ch){voiceStoppingForSend=true;voiceRunning=false;try{recognition.stop()}catch(_){finalSubmit(ch)}}else finalSubmit(ch)}
finalSubmit=async function(ch){const text=(voiceBuffers[ch]||'').trim();if(!text){toast('Сначала запишите голосовой ответ.');return}setVoiceUI(ch,'Ответ отправлен',false);if(aiReady())await evaluateWithAI(ch,text);else{if(ch==='speak')evaluateSpeak(text);if(ch==='pitch')scorePitchText(text);if(ch==='sim')evaluateSim(text);if(ch==='coach')evaluateCoachSpeechLocal(text)}}
resetSim=function(){state.simStep=0;state.messages=[];state.aiHistory=[];voiceBuffers.sim='';save();renderInvestor()}


// Production Accelerated Coach v7: silent, persistent 1/3/6-hour learning sessions.
state.accel=Object.assign({active:false,targetMin:360,startedAt:0,pausedAt:0,totalPauseMs:0,blockIndex:0,completedBlocks:0,hints:true},state.accel||{});
let accelTicker=null,accelWakeLock=null,lastAccelPhase=-1;
const ACCEL_BLOCK_MIN=20,ACCEL_BREAK_MIN=5;
const ACCEL_TASKS=[
  {view:'learn',title:'Термины',desc:'Короткие карточки и примеры.'},
  {view:'speak',title:'Голосовая практика',desc:'Объясните термин своими словами.'},
  {view:'investor',title:'AI-инвестор',desc:'Отвечайте голосом на вопросы инвестора.'},
  {view:'pitch',title:'Pitch',desc:'Проблема → решение → рынок → traction → ask.'},
  {view:'train',title:'Тесты',desc:'Ответьте и сразу разберите ошибку.'}
];
function accelElapsedMs(){const a=state.accel;if(!a.startedAt)return 0;const end=a.pausedAt||Date.now();return Math.max(0,end-a.startedAt-(a.totalPauseMs||0))}
function accelTargetMs(){return (state.accel.targetMin||360)*60000}
function accelRemainingMs(){return Math.max(0,accelTargetMs()-accelElapsedMs())}
function formatDuration(ms){const total=Math.max(0,Math.floor(ms/1000)),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),sec=total%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`:`${m}:${String(sec).padStart(2,'0')}`}
function accelCyclePosition(){const work=ACCEL_BLOCK_MIN*60000,br=ACCEL_BREAK_MIN*60000,cycle=work+br,pos=accelElapsedMs()%cycle;return {isBreak:pos>=work,remaining:(pos>=work?cycle:work)-pos}}
function accelTask(){const workBlocks=Math.floor(accelElapsedMs()/((ACCEL_BLOCK_MIN+ACCEL_BREAK_MIN)*60000));return ACCEL_TASKS[workBlocks%ACCEL_TASKS.length]}
function accelProgress(){return Math.min(100,Math.round(accelElapsedMs()/Math.max(1,accelTargetMs())*100))}
function accelIsPaused(){return !!state.accel.pausedAt}
function accelStatusText(){if(!state.accel.active)return 'Не запущен';if(accelIsPaused())return 'Пауза';return accelCyclePosition().isBreak?'Перерыв':'Сессия идёт'}
async function requestWakeLock(){if(!state.accel.active||accelIsPaused()||!('wakeLock' in navigator))return;try{if(!accelWakeLock)accelWakeLock=await navigator.wakeLock.request('screen');accelWakeLock.addEventListener?.('release',()=>{accelWakeLock=null})}catch(_){accelWakeLock=null}}
async function releaseWakeLock(){try{await accelWakeLock?.release()}catch(_){}accelWakeLock=null}
function setAccelTarget(min){if(state.accel.active){toast('Сначала завершите текущую сессию.');return}state.accel.targetMin=min;save();refreshAccelUI()}
async function startAccel(min=state.accel.targetMin||360){state.accel={...state.accel,active:true,targetMin:min,startedAt:Date.now(),pausedAt:0,totalPauseMs:0,blockIndex:0,completedBlocks:0,hints:state.accel.hints!==false};save();lastAccelPhase=-1;await requestWakeLock();startAccelTicker();refreshAccelUI();toast('Ускоренный коуч запущен')}
async function pauseAccel(){if(!state.accel.active||accelIsPaused())return;state.accel.pausedAt=Date.now();save();await releaseWakeLock();refreshAccelUI()}
async function resumeAccel(){if(!state.accel.active||!accelIsPaused())return;const now=Date.now();state.accel.totalPauseMs=(state.accel.totalPauseMs||0)+(now-state.accel.pausedAt);state.accel.pausedAt=0;save();await requestWakeLock();refreshAccelUI()}
async function stopAccel(completed=false){if(!state.accel.active)return;state.accel.active=false;state.accel.pausedAt=0;save();await releaseWakeLock();clearInterval(accelTicker);accelTicker=null;refreshAccelUI();toast(completed?'Интенсив завершён':'Сессия завершена')}
function toggleAccelHints(){state.accel.hints=state.accel.hints===false;save();refreshAccelUI()}
function openAccelTask(){if(!state.accel.active)return;go(accelTask().view)}
function accelBlockNumber(){return Math.floor(accelElapsedMs()/((ACCEL_BLOCK_MIN+ACCEL_BREAK_MIN)*60000))+1}
function maybeAdvanceAccel(){if(!state.accel.active||accelIsPaused())return;if(accelRemainingMs()<=0){stopAccel(true);return}const pos=accelCyclePosition(),phase=accelBlockNumber()*2+(pos.isBreak?1:0);if(phase!==lastAccelPhase){lastAccelPhase=phase;refreshAccelUI()}}
function accelCoachHtml(){
 const a=state.accel,pos=a.active?accelCyclePosition():{isBreak:false,remaining:ACCEL_BLOCK_MIN*60000},task=accelTask(),progress=accelProgress(),hints=a.hints!==false;
 const controls=a.active?`<div class="accel-controls-under-clock"><button class="btn secondary" onclick="resumeAccel()" ${!accelIsPaused()?'disabled':''}>Продолжить</button><button class="btn secondary" onclick="pauseAccel()" ${accelIsPaused()?'disabled':''}>Пауза</button><button class="btn" onclick="openAccelTask()">Открыть текущий блок</button><button class="btn secondary" onclick="toggleAccelHints()">${hints?'Скрыть подсказки':'Подсказки'}</button><button class="btn secondary danger-lite" onclick="stopAccel(false)">Завершить</button></div>`:'';
 return `<div class="card accel-coach ${a.active?'running':''}"><div class="accel-head"><div><span class="tag">УСКОРЕННОЕ ОБУЧЕНИЕ</span><h2>Интенсив</h2><p class="muted">1, 3 или 6 часов.</p></div><div class="accel-clock"><strong>${a.active?formatDuration(accelRemainingMs()):formatDuration(accelTargetMs())}</strong><small>${a.active?'осталось':'план'}</small>${controls}</div></div><div class="accel-targets">${[[60,'1 час'],[180,'3 часа'],[360,'6 часов']].map(([m,l])=>`<button class="${a.targetMin===m?'active':''}" onclick="setAccelTarget(${m})" ${a.active?'disabled':''}>${l}</button>`).join('')}</div>${a.active?`<div class="accel-live"><div class="row between"><strong>${accelStatusText()} · блок ${accelBlockNumber()}</strong><span>${progress}%</span></div><div class="progress"><div style="width:${progress}%"></div></div>${hints?`<div class="accel-task"><span>${pos.isBreak?'☕':'•'}</span><div><strong>${pos.isBreak?'Короткий перерыв':safe(task.title)}</strong><p>${pos.isBreak?'Можно сделать паузу, пройтись или сразу открыть следующий блок.':safe(task.desc)}</p><small>До следующего блока: ${formatDuration(pos.remaining)}</small></div></div>`:''}</div>`:`<div class="accel-preview"><p class="muted">Можно остановить и продолжить позже.</p><button class="btn accel-start" onclick="startAccel(${a.targetMin||360})">Запустить ускоренный коуч</button></div>`}</div>`
}
function refreshAccelUI(){document.querySelectorAll('[data-accel-slot]').forEach(el=>el.innerHTML=accelCoachHtml());if(state.accel.active&&!accelIsPaused())requestWakeLock()}
function startAccelTicker(){clearInterval(accelTicker);if(!state.accel.active)return;accelTicker=setInterval(()=>{maybeAdvanceAccel();refreshAccelUI()},1000);maybeAdvanceAccel()}

document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.accel.active&&!accelIsPaused())requestWakeLock()});


function installCtaHtml(){return `<div class="card install-cta"><div><span class="tag">PWA ДЛЯ ТЕЛЕФОНА</span><h2>Investor Coach как приложение</h2><p class="muted">Установите сайт на телефон: отдельная иконка, standalone-режим и офлайн-доступ к основным материалам.</p></div><button class="btn install-download" onclick="installApp()">⬇ Скачать приложение</button></div>`}
const _renderDashboardV6=renderDashboard;
renderDashboard=function(){_renderDashboardV6();const root=document.querySelector('#view-dashboard');if(root){const top=document.createElement('div');top.className='v6-dashboard-top';top.innerHTML=installCtaHtml()+`<div data-accel-slot>${accelCoachHtml()}</div>`;root.prepend(top)}setInstallState()}
const _renderRoadmapV6=renderRoadmap;
renderRoadmap=function(){_renderRoadmapV6();const root=document.querySelector('#view-roadmap');if(root){const slot=document.createElement('div');slot.setAttribute('data-accel-slot','');slot.innerHTML=accelCoachHtml();root.prepend(slot)}}
const _setInstallStateV6=setInstallState;
setInstallState=function(){_setInstallStateV6();document.querySelectorAll('.install-download').forEach(b=>{if(isStandalone()){b.textContent='✓ Приложение установлено';b.disabled=true}else{b.textContent='⬇ Скачать приложение';b.disabled=false}})}

if(state.accel.active){if(state.accel.pausedAt&&state.accel.pausedAt<state.accel.startedAt)state.accel.pausedAt=0;startAccelTicker()}

renderAll();

