const ALLOWED_ORIGINS = new Set(["https://guidoss.com","https://www.guidoss.com","http://localhost:8080","http://127.0.0.1:8080"]);
const enc=new TextEncoder();
function originFor(req){const o=req.headers.get("Origin")||"";return ALLOWED_ORIGINS.has(o)?o:"https://guidoss.com"}
function headers(origin){return {"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":origin,"Vary":"Origin","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}}
function out(data,status,origin){return new Response(JSON.stringify(data),{status,headers:headers(origin)})}
function id(prefix){return prefix+"_"+crypto.randomUUID().replaceAll("-","")}
function b64(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function randomToken(bytes=32){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return b64(a)}
async function sha256(s){return b64(await crypto.subtle.digest("SHA-256",enc.encode(s)))}
async function passwordHash(password,salt){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);return b64(await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations:210000,hash:"SHA-256"},key,256))}
function clean(s,n=120){return String(s||"").trim().slice(0,n)}
function emailOk(s){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)}
function now(){return new Date().toISOString()}
function plusDays(n){return new Date(Date.now()+n*86400000).toISOString()}
async function json(req){try{return await req.json()}catch{return {}}}
async function auth(req,env){if(!env.DB)return null;const raw=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!raw)return null;const h=await sha256(raw);return await env.DB.prepare(`SELECT u.id,u.org_id,u.email,u.name,u.role,o.name org_name,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id JOIN organizations o ON o.id=u.org_id WHERE s.token_hash=? AND s.expires_at>?`).bind(h,now()).first()}
async function issueSession(userId,env){const token=randomToken(),h=await sha256(token);await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(h,userId,plusDays(30),now()).run();return token}
function publicUser(u){return {id:u.id,orgId:u.org_id,email:u.email,name:u.name,role:u.role,orgName:u.org_name}}
function outputText(j){if(typeof j.output_text==="string")return j.output_text;for(const item of(j.output||[]))for(const c of(item.content||[]))if(c.type==="output_text"&&c.text)return c.text;return ""}
const aiSchema={type:"object",additionalProperties:false,properties:{score:{type:"integer",minimum:0,maximum:100},verdict:{type:"string"},strengths:{type:"array",items:{type:"string"},maxItems:4},improvements:{type:"array",items:{type:"string"},maxItems:5},red_flags:{type:"array",items:{type:"string"},maxItems:4},metrics:{type:"array",items:{type:"string"},maxItems:8},next_question:{type:"string"},model_answer:{type:"string"},memory_summary:{type:"string"},focus_topics:{type:"array",items:{type:"string"},maxItems:6}},required:["score","verdict","strengths","improvements","red_flags","metrics","next_question","model_answer","memory_summary","focus_topics"]};
function instructions(mode){return `Ты — institutional-grade venture investor и тренер основателя. Язык ответа — русский, профессиональные VC/SaaS термины оставляй международными. Режим: ${mode}. Оценивай прямой ответ, причинную логику, ICP, market, traction, unit economics, GTM, defensibility, team, financing logic и risks. Не выдумывай цифры. Если данных нет — отмечай gap. Следующий вопрос должен проверять самое слабое место. Score 90+ только за конкретный непротиворечивый investor-ready ответ. model_answer использует только факты пользователя; неизвестное помечай [нужна цифра].`}
async function accountRoutes(req,env,u,origin){const p=u.pathname;
 if(!env.DB)return out({error:"database_not_configured"},503,origin);
 if(p==="/api/account/register-org"){const b=await json(req),orgName=clean(b.orgName),name=clean(b.name),email=clean(b.email,180).toLowerCase(),password=String(b.password||"");if(orgName.length<2||name.length<2||!emailOk(email)||password.length<10)return out({error:"invalid_input",message:"Проверьте организацию, имя, email и пароль (минимум 10 символов)."},400,origin);const exists=await env.DB.prepare("SELECT id FROM users WHERE email=? LIMIT 1").bind(email).first();if(exists)return out({error:"email_exists"},409,origin);const oid=id("org"),uid=id("usr"),salt=randomToken(18),ph=await passwordHash(password,salt);await env.DB.batch([env.DB.prepare("INSERT INTO organizations(id,name,created_at) VALUES(?,?,?)").bind(oid,orgName,now()),env.DB.prepare("INSERT INTO users(id,org_id,email,name,role,password_hash,password_salt,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(uid,oid,email,name,"admin",ph,salt,now())]);const token=await issueSession(uid,env);return out({token,user:{id:uid,orgId:oid,email,name,role:"admin",orgName}},201,origin)}
 if(p==="/api/account/login"){const b=await json(req),email=clean(b.email,180).toLowerCase(),password=String(b.password||"");const x=await env.DB.prepare(`SELECT u.*,o.name org_name FROM users u JOIN organizations o ON o.id=u.org_id WHERE u.email=? LIMIT 1`).bind(email).first();if(!x||await passwordHash(password,x.password_salt)!==x.password_hash)return out({error:"invalid_credentials"},401,origin);const token=await issueSession(x.id,env);return out({token,user:publicUser(x)},200,origin)}
 if(p==="/api/account/join"&&req.method==="POST"){const b=await json(req),code=clean(b.code,200),name=clean(b.name),email=clean(b.email,180).toLowerCase(),password=String(b.password||"");if(!code||name.length<2||!emailOk(email)||password.length<10)return out({error:"invalid_input"},400,origin);const inv=await env.DB.prepare("SELECT * FROM invites WHERE code_hash=? AND used_by IS NULL AND expires_at>?").bind(await sha256(code),now()).first();if(!inv)return out({error:"invalid_invite"},400,origin);const uid=id("usr"),salt=randomToken(18),ph=await passwordHash(password,salt);try{await env.DB.prepare("INSERT INTO users(id,org_id,email,name,role,password_hash,password_salt,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(uid,inv.org_id,email,name,inv.role,ph,salt,now()).run()}catch{return out({error:"email_exists"},409,origin)}await env.DB.prepare("UPDATE invites SET used_by=? WHERE code_hash=?").bind(uid,await sha256(code)).run();const row=await env.DB.prepare(`SELECT u.*,o.name org_name FROM users u JOIN organizations o ON o.id=u.org_id WHERE u.id=?`).bind(uid).first(),token=await issueSession(uid,env);return out({token,user:publicUser(row)},201,origin)}
 const me=await auth(req,env);if(!me)return out({error:"unauthorized"},401,origin);
 if(p==="/api/account/me")return out({user:publicUser(me)},200,origin);
 if(p==="/api/account/logout"){const raw=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(raw)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha256(raw)).run();return out({ok:true},200,origin)}
 if(p==="/api/account/state"&&req.method==="GET"){const r=await env.DB.prepare("SELECT state_json,updated_at FROM learning_state WHERE user_id=?").bind(me.id).first();return out({state:r?JSON.parse(r.state_json):null,updatedAt:r?.updated_at||null},200,origin)}
 if(p==="/api/account/state"&&req.method==="POST"){const b=await json(req),s=b.state;if(!s||typeof s!=="object")return out({error:"state_required"},400,origin);const payload=JSON.stringify(s);if(payload.length>800000)return out({error:"state_too_large"},413,origin);await env.DB.prepare(`INSERT INTO learning_state(user_id,state_json,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET state_json=excluded.state_json,updated_at=excluded.updated_at`).bind(me.id,payload,now()).run();return out({ok:true,updatedAt:now()},200,origin)}
 if(p==="/api/account/invite"&&req.method==="POST"){if(!["admin","manager"].includes(me.role))return out({error:"forbidden"},403,origin);const b=await json(req),role=b.role==="manager"&&me.role==="admin"?"manager":"learner",code=randomToken(12),hash=await sha256(code);await env.DB.prepare("INSERT INTO invites(code_hash,org_id,role,expires_at,created_by,created_at) VALUES(?,?,?,?,?,?)").bind(hash,me.org_id,role,plusDays(7),me.id,now()).run();return out({code,role,expiresAt:plusDays(7)},201,origin)}
 if(p==="/api/account/team"&&req.method==="GET"){if(!["admin","manager"].includes(me.role))return out({error:"forbidden"},403,origin);const rows=await env.DB.prepare(`SELECT u.id,u.name,u.email,u.role,ls.updated_at,ls.state_json FROM users u LEFT JOIN learning_state ls ON ls.user_id=u.id WHERE u.org_id=? ORDER BY u.created_at`).bind(me.org_id).all();const members=(rows.results||[]).map(x=>{let st={};try{st=x.state_json?JSON.parse(x.state_json):{}}catch{}const assessments=st.enterprise?.assessments||[],last=[...assessments].reverse().find(a=>a.kind==="final")||[...assessments].reverse().find(a=>a.kind==="baseline");return {id:x.id,name:x.name,email:x.email,role:x.role,updatedAt:x.updated_at,assessment:last?last.score:null,answers:st.total||0,testScore:st.total?Math.round((st.correct||0)/st.total*100):null,coachTerms:Object.keys(st.coachStats||{}).length}});return out({members},200,origin)}
 return out({error:"not_found"},404,origin)
}
export default {async fetch(request,env){const origin=originFor(request);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:headers(origin)});const u=new URL(request.url);if(u.pathname.startsWith("/api/account/"))return accountRoutes(request,env,u,origin);if(request.method!=="POST")return out({error:"Method not allowed"},405,origin);if(!env.OPENAI_API_KEY)return out({error:"OPENAI_API_KEY is not configured"},500,origin);
if(u.pathname==="/api/transcribe"){try{const incoming=await request.formData(),file=incoming.get("file");if(!file||typeof file==="string")return out({error:"audio file required"},400,origin);if(file.size>24*1024*1024)return out({error:"audio too large"},413,origin);const fd=new FormData();fd.append("file",file,file.name||"answer.webm");fd.append("model",env.TRANSCRIBE_MODEL||"gpt-4o-transcribe");fd.append("language",incoming.get("language")||"ru");fd.append("prompt","Русская речь основателя стартапа. Точно сохраняй числа и международные термины VC/SaaS: SAFE, cap table, valuation, dilution, runway, burn rate, CAC, LTV, MRR, ARR, NRR, GRR, churn, retention, traction, TAM, SAM, SOM, ICP, PMF, GTM, SaaS, unit economics, gross margin, EBITDA, pitch, term sheet, due diligence.");const r=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`},body:fd}),text=await r.text();if(!r.ok)return out({error:"transcription_failed",detail:text.slice(0,300)},502,origin);return out({text:JSON.parse(text).text||""},200,origin)}catch(e){return out({error:"transcription_exception",detail:String(e).slice(0,200)},500,origin)}}
if(u.pathname==="/api/coach"){try{const b=await json(request),transcript=String(b.transcript||"").slice(0,16000);if(!transcript)return out({error:"transcript required"},400,origin);const input=`Накопленная память проекта:\n${String(b.memory||"нет").slice(0,6000)}\n\nПоследняя история:\n${JSON.stringify(b.history||[]).slice(0,7000)}\n\nСлабые темы: ${JSON.stringify(b.weak_topics||[])}\nДень курса: ${b.course_day||1}\nКонтекст: ${JSON.stringify(b.context||{}).slice(0,4000)}\n\nОтвет основателя:\n${transcript}`;const body={model:env.COACH_MODEL||"gpt-5.6-terra",instructions:instructions(String(b.mode||"sim")),input,text:{format:{type:"json_schema",name:"investor_coach_feedback",strict:true,schema:aiSchema}},max_output_tokens:1800};const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${env.OPENAI_API_KEY}`},body:JSON.stringify(body)}),raw=await r.text();if(!r.ok)return out({error:"coach_failed",detail:raw.slice(0,400)},502,origin);const txt=outputText(JSON.parse(raw));if(!txt)return out({error:"empty_model_output"},502,origin);return out(JSON.parse(txt),200,origin)}catch(e){return out({error:"coach_exception",detail:String(e).slice(0,240)},500,origin)}}return out({error:"Not found"},404,origin)}};
