const JSON_HEADERS={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"no-referrer"};
const aiSchema={type:"object",additionalProperties:false,properties:{score:{type:"integer",minimum:0,maximum:100},verdict:{type:"string"},strengths:{type:"array",items:{type:"string"}},improvements:{type:"array",items:{type:"string"}},red_flags:{type:"array",items:{type:"string"}},model_answer:{type:"string"},next_question:{type:"string"},memory_summary:{type:"string"},focus_topics:{type:"array",items:{type:"string"}}},required:["score","verdict","strengths","improvements","red_flags","model_answer","next_question","memory_summary","focus_topics"]};
function allowed(req,env){const o=req.headers.get("Origin")||"";const list=String(env.ALLOWED_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean);return !o||list.includes(o)}
function headers(req,env){const h=new Headers(JSON_HEADERS),o=req.headers.get("Origin")||"";if(o&&allowed(req,env))h.set("Access-Control-Allow-Origin",o);h.set("Vary","Origin");h.set("Access-Control-Allow-Headers","Content-Type,Authorization,X-Request-Id");h.set("Access-Control-Allow-Methods","GET,POST,OPTIONS");return h}
function out(req,env,data,status=200,rid=""){const h=headers(req,env);if(rid)h.set("X-Request-Id",rid);return new Response(JSON.stringify(data),{status,headers:h})}
function requestId(req){const x=(req.headers.get("X-Request-Id")||"").trim();return /^[A-Za-z0-9._:-]{8,100}$/.test(x)?x:crypto.randomUUID()}
async function json(req){try{return await req.json()}catch{return {}}}
function outputText(r){if(typeof r.output_text==="string")return r.output_text;for(const x of r.output||[])for(const c of x.content||[])if(typeof c.text==="string")return c.text;return ""}
function instructions(mode){return `Ты — профессиональный тренер по общению с инвесторами. Язык — русский; международные VC/SaaS термины оставляй как принято в индустрии. Режим: ${mode}. Главная цель — быстро улучшить профессиональную речь. Оцени: понял ли человек термин, употребил ли его в правильном контексте, дал ли цифру/период/сегмент там, где это нужно, объяснил ли причинную связь и ответил ли именно на вопрос инвестора. Не выдумывай факты пользователя. Если данных нет — прямо укажи, чего не хватает. model_answer должен быть коротким образцом профессионального ответа без выдуманных цифр. Для режима coach дай конкретную обратную связь только по текущему термину и не повторяй учебник целиком.`}
export default {async fetch(req,env){const rid=requestId(req),url=new URL(req.url),started=Date.now();try{
 if(req.method==="OPTIONS"){if(!allowed(req,env))return out(req,env,{error:"origin_not_allowed"},403,rid);return new Response(null,{status:204,headers:headers(req,env)})}
 if(!allowed(req,env))return out(req,env,{error:"origin_not_allowed"},403,rid);
 if(url.pathname==="/healthz")return out(req,env,{ok:true,service:"investor-coach-ai",version:"10.0.0"},200,rid);
 if(url.pathname==="/readyz")return out(req,env,{ok:!!env.OPENAI_API_KEY,openaiConfigured:!!env.OPENAI_API_KEY,version:"10.0.0"},env.OPENAI_API_KEY?200:503,rid);
 if(url.pathname==="/api/transcribe"&&req.method==="POST"){if(!env.OPENAI_API_KEY)return out(req,env,{error:"ai_not_configured"},503,rid);const incoming=await req.formData(),file=incoming.get("file");if(!file||typeof file==="string")return out(req,env,{error:"audio_file_required"},400,rid);if(file.size>24*1024*1024)return out(req,env,{error:"audio_too_large"},413,rid);const fd=new FormData();fd.append("file",file,file.name||"answer.webm");fd.append("model",env.TRANSCRIBE_MODEL||"gpt-4o-transcribe");fd.append("language",incoming.get("language")||"ru");fd.append("prompt","Русская деловая речь. Точно сохраняй числа и термины: SAFE, cap table, valuation, dilution, runway, burn rate, CAC, LTV, MRR, ARR, NRR, GRR, churn, retention, traction, TAM, SAM, SOM, ICP, PMF, GTM, SaaS, unit economics, gross margin, EBITDA, pitch, term sheet, due diligence.");const r=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`},body:fd}),raw=await r.text();if(!r.ok)return out(req,env,{error:"transcription_failed",detail:raw.slice(0,300)},502,rid);return out(req,env,{text:JSON.parse(raw).text||""},200,rid)}
 if(url.pathname==="/api/coach"&&req.method==="POST"){if(!env.OPENAI_API_KEY)return out(req,env,{error:"ai_not_configured"},503,rid);const b=await json(req),transcript=String(b.transcript||"").slice(0,16000);if(!transcript)return out(req,env,{error:"transcript_required"},400,rid);const input=`Память проекта:\n${String(b.memory||"нет").slice(0,6000)}\n\nИстория:\n${JSON.stringify(b.history||[]).slice(0,6000)}\n\nСлабые темы: ${JSON.stringify(b.weak_topics||[])}\nКонтекст: ${JSON.stringify(b.context||{}).slice(0,5000)}\n\nОтвет пользователя:\n${transcript}`;const body={model:env.COACH_MODEL||"gpt-5.6-terra",instructions:instructions(String(b.mode||"sim")),input,text:{format:{type:"json_schema",name:"investor_coach_feedback",strict:true,schema:aiSchema}},max_output_tokens:1400};const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${env.OPENAI_API_KEY}`},body:JSON.stringify(body)}),raw=await r.text();if(!r.ok)return out(req,env,{error:"coach_failed",detail:raw.slice(0,300)},502,rid);const text=outputText(JSON.parse(raw));if(!text)return out(req,env,{error:"empty_model_output"},502,rid);return out(req,env,JSON.parse(text),200,rid)}
 return out(req,env,{error:"not_found"},404,rid)
 }catch(e){console.log(JSON.stringify({type:"error",request_id:rid,path:url.pathname,error:String(e).slice(0,400),duration_ms:Date.now()-started}));return out(req,env,{error:"internal_error",request_id:rid},500,rid)}}};